gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#0078d4"
    inactiveBorderColor:
      - "#2d2d2d"
git:
  paging:
    colorArg: always
    pager: ~/.local/share/mise/shims/delta --dark --paging=never --line-numbers --syntax-theme="Visual Studio Dark+"
