gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#58a6ff"
      - bold
    inactiveBorderColor:
      - "#30363d"
    selectedLineBgColor:
      - "#161b22"
    selectedRangeBgColor:
      - "#161b22"
git:
  paging:
    colorArg: always
    pager: ~/.local/share/mise/shims/delta --dark --paging=never --line-numbers --syntax-theme="Visual Studio Dark+"
